[tools]
biome = "2.1.1"
claude = "latest"
delta = "latest"
fzf = "latest"
gh = "latest"
go = "1.25"
"go:github.com/cespare/reflex" = "latest"
jq = "latest"
lazygit = "latest"
node = "22"
pnpm = "10"
ripgrep = "latest"
tmux = "latest"
usage = "latest"
zoxide = "latest"

[settings]
experimental = true
